apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-1
  namespace: default
spec:
  upstream:
    url: "http://abc.ef"
    preserveHost: false
  match:
    url: "http://gh.ij"
    methods: ["GET", "POST"]
  authenticators:
  - handler: anonymous
  authorizer:
    handler: allow
  mutator:
    handler: noop
    config: {}
